services:
  - type: web
    name: xray-analyzer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true 