services:
  - type: web
    name: xray-analyzer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1 